#!/usr/bin/env python3
"""Generate feature_map.h: model feature order → ARM feature order.

MANDATORY: Run this before deploying ANY new XGB model to ARM.
The model expects features in training order. ARM extracts in a different order.
This script bridges them.

Usage:
    python3 gen_feature_map.py model.json feature_map.h

Output: feature_map.h with FEAT_MAP[] and MODEL_FEAT_COUNT
"""

import sys
import xgboost as xgb

# ARM feature extraction order (ip_god.c flow_to_features)
# Must match exactly what ip_god.c puts in feat[0..74]
ARM_FEATURES = [
    # F1: Protocol (3)
    'dst_port', 'ip_proto', 'app_proto',
    # F2: Volume (8)
    'pkts_fwd', 'pkts_rev', 'bytes_fwd', 'bytes_rev',
    'bytes_per_pkt_fwd', 'bytes_per_pkt_rev', 'pkt_ratio', 'byte_ratio',
    # F3: Timing (10)
    'duration_ms', 'rtt_ms', 'iat_fwd_mean_ms', 'iat_fwd_std_ms',
    'think_time_mean_ms', 'think_time_std_ms', 'iat_to_rtt', 'pps', 'bps', 'payload_rtt_ratio',
    # F4: Packet Size Shape (14)
    'n_events', 'fwd_size_mean', 'fwd_size_std', 'fwd_size_min', 'fwd_size_max',
    'rev_size_mean', 'rev_size_std', 'rev_size_max',
    'hist_tiny', 'hist_small', 'hist_medium', 'hist_large', 'hist_full', 'frac_full',
    # F5: TCP Behavior (11)
    'syn_count', 'fin_count', 'rst_count', 'psh_count', 'ack_only_count',
    'conn_state', 'rst_frac', 'syn_to_data', 'psh_burst_max', 'retransmit_est', 'window_size_init',
    # F6: Payload Content (8)
    'entropy_first', 'entropy_fwd_mean', 'entropy_rev_mean',
    'printable_frac', 'null_frac', 'byte_std', 'high_entropy_frac', 'payload_len_first',
    # F7: Protocol Fingerprints (15)
    'ja3_freq', 'tls_version', 'tls_cipher_count', 'tls_ext_count', 'tls_has_sni',
    'hassh_freq', 'ssh_kex_count',
    'http_method', 'http_uri_len', 'http_header_count', 'http_ua_freq', 'http_has_body', 'http_status',
    'dns_qtype', 'dns_qname_len',
    # F8: Source Behavior (6)
    'src_flow_count', 'src_unique_ports', 'src_unique_protos', 'src_unique_dsts', 'src_span_min', 'src_avg_pps',
]

ARM_INDEX = {name: i for i, name in enumerate(ARM_FEATURES)}


def main():
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} model.json output.h")
        sys.exit(1)

    model_path, output_path = sys.argv[1], sys.argv[2]

    bst = xgb.Booster()
    bst.load_model(model_path)

    model_names = bst.feature_names
    if not model_names:
        print("ERROR: model has no feature_names")
        sys.exit(1)

    print(f"Model: {len(model_names)} features")
    print(f"ARM:   {len(ARM_FEATURES)} features")

    mapping = []
    for i, name in enumerate(model_names):
        if name in ARM_INDEX:
            mapping.append(ARM_INDEX[name])
        else:
            print(f"  WARNING: '{name}' not in ARM order → -1")
            mapping.append(-1)

    with open(output_path, 'w') as f:
        f.write(f"/* Auto-generated by gen_feature_map.py */\n")
        f.write(f"/* Model: {model_path} ({len(model_names)} features) */\n")
        f.write(f"/* ARM: {len(ARM_FEATURES)} features */\n")
        f.write(f"/* RUN THIS BEFORE EVERY MODEL DEPLOY */\n\n")
        f.write(f"#ifndef FEATURE_MAP_H\n#define FEATURE_MAP_H\n\n")
        f.write(f"#define MODEL_FEAT_COUNT {len(model_names)}\n\n")
        f.write(f"static const int FEAT_MAP[{len(model_names)}] = {{\n")
        for i, (name, arm_idx) in enumerate(zip(model_names, mapping)):
            f.write(f"    {arm_idx:3d},  /* [{i:2d}] {name} */\n")
        f.write(f"}};\n\n")
        f.write(f"#endif /* FEATURE_MAP_H */\n")

    print(f"Written: {output_path}")
    print(f"Mapped: {sum(1 for m in mapping if m >= 0)}/{len(model_names)}")


if __name__ == '__main__':
    main()
